Add task 9-2
danprzy/js-exercises pull request #2
Opened 2018-04-04 16:06 UTC by danprzy

2018-04-05 14:08 UTC, mentor-kk requested changes

2018-04-05 14:08 UTC, mentor-kk commented on arrays/scripts.js
> +var newName = 'Ola'
śrendik

2018-04-05 14:08 UTC, mentor-kk commented on arrays/scripts.js
> +    var x = allNames.push(newName);
1. czy wiesz czym jest `x` w tym wypadku?
2. mając tą wiedzę, czy jest on Ci do czegoś potrzebny?

Do wyrzucenia / ewentualnego przegadania na rozmowie

2018-04-06 09:43 UTC, danprzy commented on arrays/scripts.js
> +    var x = allNames.push(newName);
1. var x jest deklaracją zmiennej
2 .fakt, chyba nie jest mi to do niczego potrzebne w tym miejscu.
Zmieniłam, dodałam nowy commit

2018-06-26 17:33 UTC, merged